#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
#
# drvhsl: convert a .hslc file into a C++ module that can provide
# those binary blobs to code.

import argparse
from hslcpackager import *
from pyhslcore import *
from pathlib import Path

class DrvHslConfig:
    """
    Configuration options for this tool.
    """

    __slots__ = (
        'input_file',           # Input .hslc file to process.
        'output_directory',     # Directory to receive output files.
        'output_basename',      # Basename of the output files (e.g. <output_basename>.cpp)
        'index_prefix',         # Naming prefix for the constants that index the blobs.
        'namespace',            # Optional namespace for the generated code.
        'logger',               # Logger to use for logging.
    )

    def __init__(self):
        self.input_file       = f'out.{HSL_CONTAINER_FILE_EXTENSION}'
        self.output_directory = '.'
        self.output_basename  = None  # Will default to input file's basename
        self.index_prefix     = 'HSL_BLOB_'
        self.namespace        = None  # No namespace by default
        self.logger           = None

class DrvHsl:
    """
    Tool to convert a .hslc file into C++ helper code
    """

    def __init__(self, config: DrvHslConfig):
        self.config  = config

    def write_hex_bytes(self, file, blob):
        for n in range(len(blob)):
            if n % 16 == 0:
                file.write('\n    ')
            file.write('0x{:02x}, '.format(blob[n] & 0xff))

    def create_hpp_file(self, path: Path, index_value_map: dict, index_name_map: dict):
        guard_name = f"HSL_{path.stem.upper()}_HPP"

        with path.open('w') as file:
            file.write(f'''// GENERATED BY DRVHSL

#ifndef {guard_name}
#define {guard_name}

#include <cstdint>

#include "uddf/cdi/hal/HSLStaticSequence.hpp"

''')
            namespaces = []
            if self.config.namespace:
                namespaces = self.config.namespace.split('::')
                for ns in namespaces:
                    file.write(f'namespace {ns} {{\n')
                file.write('\n')

            for name, blob in index_name_map.items():
                blob_size = len(blob.bytecode)
                var_name = blob.name

                file.write(f'''/**
 * @brief HSL bytecode sequence for {blob.name}
 */
inline constexpr uddf::cdi::HSLStaticSequence<{blob_size}U> {var_name} {{ {{{{''')
                self.write_hex_bytes(file, blob.bytecode)
                file.write('\n}} };\n\n')

            if namespaces:
                for ns in reversed(namespaces):
                    file.write(f'}} // namespace {ns}\n')

            file.write(f'''
#endif // {guard_name}
''')

    def execute(self):
        cfg = self.config
        output_dir_path = Path(cfg.output_directory).resolve()
        if not output_dir_path.is_dir():
            raise PyHslException(f'{str(output_dir_path)} is not a directory')

        input_file_path = Path(cfg.input_file).resolve()
        if not input_file_path.is_file():
            raise PyHslException(f'{str(input_file_path)} is not a valid file')

        # Use input file's basename by default if not specified
        if cfg.output_basename is None:
            cfg.output_basename = input_file_path.stem

        hpp_path = (output_dir_path/Path(f'{cfg.output_basename}.hpp')).resolve()

        packager = HslcPackager()
        with open(input_file_path, 'rb') as f:
            packager.unpackage(f)

        index_name_map  = {cfg.index_prefix + blob.name.upper() : blob for blob in packager.blobs.values()}
        index_value_map = {list(index_name_map.keys())[i] : i for i in range(len(index_name_map.keys()))}

        self.create_hpp_file(hpp_path, index_value_map, index_name_map)

if __name__ == "__main__":
    logging.basicConfig()
    mylogger = logging.getLogger('pyhsl')
    mylogger.setLevel(logging.INFO)

    config = DrvHslConfig()

    parser = argparse.ArgumentParser(description='Convert a .hslc file into C++ code to retrieve HSL bytecode blobs')
    parser.add_argument('-i', '--input', help=f'source .{HSL_CONTAINER_FILE_EXTENSION} file to process',
                        default=config.input_file,
                        metavar='source-file')
    parser.add_argument('-d', '--directory', help=f'output directory for generated files',
                        default=config.output_directory,
                        metavar='output-directory')
    parser.add_argument('-b', '--basename', help='basename for generated files (defaults to input filename)',
                        default=config.output_basename,
                        metavar='basename')
    parser.add_argument('-p', '--prefix', help='prefix for generated constants',
                        default=config.index_prefix,
                        metavar='prefix')
    parser.add_argument('-n', '--namespace', help='namespace for the generated code (e.g., "mydriver::hsl")',
                        default=config.namespace,
                        metavar='namespace')
    parser.add_argument('-l', '--loglevel', help='Logging level',
                        default='warning', choices=('debug', 'info', 'warning', 'error', 'critical'))
    args = parser.parse_args()

    mylogger.setLevel(args.loglevel.upper())

    config.input_file       = args.input
    config.output_directory = args.directory
    config.output_basename  = args.basename
    config.index_prefix     = args.prefix
    config.namespace        = args.namespace
    config.logger           = mylogger

    drvhsl = DrvHsl(config)
    drvhsl.execute()
