# SPDX-FileCopyrightText: Copyright (c) 2023-2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# See README.md for detailed information.

ARG CONTAINER_VERSION=invalid
FROM ${CONTAINER_VERSION} AS base

# build container
FROM base AS builder

RUN apt-get update \
    && apt-get install -y python3-setuptools \
    && rm -rf /var/lib/apt/lists/*

# RUN apt-get update && apt-get install -y \
#     git \
#     cmake \
#     libssl-dev \
#     libusb-1.0-0-dev \
#     libglfw3-dev \
#     libgtk-3-dev \
#     pkg-config \
#     && rm -rf /var/lib/apt/lists/*

# # Clone librealsense
# RUN git clone https://github.com/IntelRealSense/librealsense.git /opt/librealsense \
#     && cd /opt/librealsense \
#     && git checkout master

# # Build it
# RUN cd /opt/librealsense \
#     && mkdir build && cd build \
#     && cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=false -DBUILD_GRAPHICAL_EXAMPLES=false -DBUILD_WITH_DDS=ON \
#     && make -j$(nproc) \
#     && make install \
#     && ldconfig

ADD . /opt/hololink/

# See build.sh for why INSTALL_ENVIRONMENT is here.
ARG INSTALL_ENVIRONMENT=""
RUN cd /opt/hololink/python \
    && $INSTALL_ENVIRONMENT pip3 wheel -v .

# Build C++ tools
RUN apt-get update \
    && apt-get install -y build-essential cmake \
    && rm -rf /var/lib/apt/lists/*

# Build tools with CMake
RUN cd /opt/hololink \
    && mkdir -p build \
    && cd build \
    && cmake -DHOLOLINK_BUILD_ONLY_NATIVE=ON .. \
    && make -j$(nproc) \
    && make install DESTDIR=/opt/hololink/tools

# demo container
FROM base AS demo

# set proxy settings
ENV http_proxy=${http_proxy}
ENV https_proxy=${https_proxy}
ENV HTTP_PROXY=${HTTP_PROXY}
ENV HTTPS_PROXY=${HTTPS_PROXY}
ENV no_proxy=${no_proxy}
ENV NO_PROXY=${NO_PROXY}

RUN python3 -m pip install --upgrade pip
RUN pip3 install pytest pytest-timeout

# net-tools gives us the "arp" command
# iputils-ping gives us the "ping" command
RUN apt-get update \
    && apt-get install -y net-tools iputils-ping iproute2 libusb-1.0-0 libgl1 \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -y python3-requests python3-yaml \
    && rm -rf /var/lib/apt/lists/*

# install the wheel we build before
COPY --from=builder /opt/hololink/python/hololink-*.whl /tmp/wheel/
RUN WHEEL=$(find /tmp/wheel -type f -name "hololink-*.whl") \
    && pip3 install ${WHEEL}

# Install the C++ tools
COPY --from=builder /opt/hololink/tools/usr/local/ /usr/local/

# # Copy RealSense runtime libraries from builder
# COPY --from=builder /usr/local/lib/ /usr/local/lib/
# COPY --from=builder /usr/local/include/ /usr/local/include/
# COPY --from=builder /usr/local/bin/ /usr/local/bin/
# COPY --from=builder /usr/local/share/ /usr/local/share/

# # Make sure dynamic linker sees the libraries
# RUN ldconfig

# Due to import issues with 13.0 downgrade to 12.9
# https://github.com/NVIDIA/cuda-python/issues/476
RUN pip uninstall -y cuda-python cuda-bindings cuda-core && \
    pip install --no-cache-dir cuda-python==12.9 cuda-core
