#!/bin/bash
# stage2_720p.sh [secs] — Stage 2: 2 cameras x (depth+RGB+IR) = 6 streams @ 720p30 over 4 MIPI lanes.
#
# Same mechanism as stage3_720p.sh, different shape :
#   deser 6-pipe map   D457_MAP_LINKS=2 D457_MAP_STREAMS=3   (+ the PyHSL hslc-cache force)
#   query              3-sensor (depth,rgb,ir) at enableMasks 0x0011 -> framework replicates it
#                      across links 0 and 1. Generated by tests/lib/common.sh gen_query so we do NOT
#                      depend on query/d457_query.cpp (which carries the WIP IMU sensorInfo that the
#                      SIPL ICP rejects on minimum frame height).
#   nvsipl_camera      PATCHED build (per-link VC + i2c offset) -- required for link 1.
set -u
export RIG_SUDO_PW="${RIG_SUDO_PW:-}"   # set to the rig sudo password for non-interactive sudo
echo "$RIG_SUDO_PW" | sudo -S -v 2>/dev/null
SECS="${1:-15}"
S=~/sipl_full/usr/src/jetson_sipl_api/sipl
APP=$S/samples/camera/build_dbg/nvsipl_camera
LOG=/tmp/live/run.log
STREAMS="depth,rgb,ir"
MASK=0x0011

echo "######## STAGE 2: 2 cams x depth+rgb+ir = 6 streams @ 1280x720@30, 4 lanes ########"

# --- 1. deser: 6-pipe map. Cache force is mandatory (make regenerates PyHSL only on .py mtime). ---
rm -f "$S/build/uddf/drivers/deserializers/MAX96712/hsl_gen/MAX967XXHsl.hslc"
touch "$S/uddf/drivers/deserializers/MAX967XX/MAX967XXHsl.py"
cd "$S" || exit 1
echo ">> building deser (D457_MAP_LINKS=2 D457_MAP_STREAMS=3)"
if ! D457_MAP_LINKS=2 D457_MAP_STREAMS=3 D457_DPHY_RATE_100M=${D457_DPHY_RATE_100M:-25} \
        ~/build_deploy.sh -c driver,deser > /tmp/s2_build.log 2>&1; then
    echo "BUILD FAILED:"; tail -25 /tmp/s2_build.log; exit 1
fi
SEQ=$(awk '/ set_mipi_d_phy \{/,/"set_mipi_d_phy"\};/' \
      "$S/build/uddf/drivers/deserializers/MAX96712/hsl_gen/MAX967XXHsl.hpp" | tr -d ' \n')
echo "   lane cfg: 0x094A -> $(echo "$SEQ" | grep -o '0x09U,0x4aU,0x..U') | 0x0418 -> $(echo "$SEQ" | grep -o '0x04U,0x18U,0x..U')"

# --- 2. query: 3 sensors, mask 0x0011 ---
echo ">> building + installing the 3-sensor query at mask $MASK"
cd ~/d457_tests || exit 1
. lib/common.sh
export D457_DPHY_RATE=$(( ${D457_DPHY_RATE_100M:-25} * 100000 ))
export D457_MASK=$MASK
gen_query depth rgb ir || { echo "QUERY BUILD FAILED"; exit 1; }
echo -n "   query: "; strings /usr/lib/nvsipl_drv/libnvsipl_qry_d457.so \
    | grep -oE '"enableMasks": \[ "[^"]*"|"dphyRate": [0-9]*|"lanes": [0-9]*' | tr '\n' ' '; echo

# --- 3. patched sample app ---
echo ">> re-patching + rebuilding nvsipl_camera (per-link VC + i2c offset)"
bash ~/repatch2_nvsipl_main.sh 2>&1 | tail -2

# --- 4. run ---
ensure_tmpfs
sudo rm -f "$LOG"
echo ">> DS5 PoC power-cycle"
power_cycle_ds5
DMARK="STAGE2_${RANDOM}_${RANDOM}"; sudo sh -c "echo $DMARK > /dev/kmsg" 2>/dev/null
echo ">> running ${SECS}s ..."
    # shellcheck disable=SC2024  # the redirect is intentionally the invoking user: the log lives on a
    # user-writable tmpfs, and piping nvsipl_camera through `sudo tee` would put an extra process in
    # a path that can emit tens of MB/s on failure.
sudo env D457_STREAMS="$STREAMS" D457_WIDTH=1280 D457_HEIGHT=720 D457_FPS=30.0 \
    timeout $((SECS + 25)) "$APP" -H -R -0 -1 -2 -m $MASK -c D457_Camera -r "$SECS" -s \
    > "$LOG" 2>&1
sudo pkill -9 -x nvsipl_camera 2>/dev/null; sleep 1

# --- 5. assert all 6 ---
MINF=$(( SECS * 25 )); OK=1
echo "   --- per-sensor (need >= ${MINF} frames, 0 drops) ---"
for i in $(seq 0 5); do
    LINE=$(grep -E "Sensor ${i}[[:space:]]+Frame captured:" "$LOG" | tail -1)
    FC=$(echo "$LINE" | grep -oE 'Frame captured: [0-9]+' | grep -oE '[0-9]+$')
    FD=$(echo "$LINE" | grep -oE 'Frame drops: [0-9]+'    | grep -oE '[0-9]+$')
    CAM=$((i / 3)); ST=$(echo "$STREAMS" | cut -d, -f$(( i % 3 + 1 )))
    if [ -z "${FC:-}" ]; then
        echo "   S$i (cam$CAM $ST): NO FRAMES"; OK=0
    else
        # App's own steady-state fps; skip each sensor's FIRST sample (start-up backlog / partial
        # interval inflates it). frames/SECS is NOT a rate here -- links start staggered.
        FPS=$(grep -E "Sensor${i}_Out0.*Frame rate" "$LOG" | awk '{print $NF}' | tail -n +2 \
              | sort -n | awk '{v[NR]=$1} END{if(NR)printf "%.2f", v[int((NR+1)/2)]; else printf "n/a"}')
        MARK="ok "; { [ "$FC" -lt "$MINF" ] || [ "${FD:-1}" != "0" ]; } && { MARK="BAD"; OK=0; }
        echo "   S$i (cam$CAM $ST): $MARK frames=$FC  steady fps=${FPS}  drops=${FD:-?}"
    fi
done
FAULTS=$(sudo dmesg 2>/dev/null | sed -n "/$DMARK/,\$p" | grep -icE 'chansel|pix_short|fault')
echo "   Tegra-VI faults since run start: $FAULTS"
[ "${FAULTS:-0}" != "0" ] && OK=0
sudo dmesg 2>/dev/null | grep -E 'Partition: CIL|Physical rate' | tail -2 | sed 's/^/   /'
if [ "$OK" = "1" ]; then echo "   ✅ STAGE 2 @720p30 PASS (6/6)"; else
    echo "   ❌ STAGE 2 @720p30 FAIL"; grep -iE 'error|fail|NOTIF_ERROR' "$LOG" | head -6 | sed 's/^/      /'
fi
exit $((1 - OK))
