# common.sh — shared helpers for the D457 SIPL streaming tests (run ON the rig).
#
# These are HARDWARE integration tests: they drive the real GMSL/SIPL stack on fw-advantech-thor-1.
# Each test selects a stream subset, (re)builds the matching query plugin, runs nvsipl_camera, and
# asserts every expected sensor captured frames at ~30 fps with ZERO drops and ZERO Tegra-VI faults.
#
# Stream model (post pipe-per-VC fix): each stream rides its CANONICAL virtual channel —
#   depth -> VC0, rgb -> VC1, ir -> VC2 — fixed by the SerDes pipe DT filters. The driver picks the
#   per-deviceIndex stream from D457_STREAMS (comma list); the query declares one sensorInfo per
#   stream at its canonical VC. gen_query + D457_STREAMS are always built from the same stream list.
#
# Prereqs on the rig: booted into the `sipl-d457` extlinux label; the D457 SIPL drivers/patches
# installed in /usr/lib/nvsipl_drv/. The stock system libnvsipl.so is used -- the old lanes=2
# binary patch (~/sipl_libs on LD_LIBRARY_PATH) is retired now that the deser drives 4 lanes.

set -u

NVSIPL_DRV=/usr/lib/nvsipl_drv
QRY_SRC=/tmp/d457_tests/d457_query_gen.cpp
QRY_SO=$NVSIPL_DRV/libnvsipl_qry_d457.so
RUN_LOG=/tmp/live/run.log
MUX_POC_BUS=9
MUX_POC_ADDR=0x28           # MAX20087 PoC power controller (DS5 power-cycle)

PASS_COUNT=0
FAIL_COUNT=0

# Prime sudo (the rig helpers — DS5 power-cycle, nvsipl_camera, dmesg, installing the query .so —
# need root). Set RIG_SUDO_PW to authenticate non-interactively; otherwise sudo must already be
# usable (NOPASSWD, or a primed `sudo -v`). One prime covers a full test file (< sudo's 15-min TTL).
if [ -n "${RIG_SUDO_PW:-}" ]; then
    echo "$RIG_SUDO_PW" | sudo -S -v 2>/dev/null || true
fi

log()  { echo "[$(date '+%H:%M:%S')] $*"; }
pass() { PASS_COUNT=$((PASS_COUNT+1)); echo "  ✅ PASS: $*"; }
fail() { FAIL_COUNT=$((FAIL_COUNT+1)); echo "  ❌ FAIL: $*"; }

# Ensure a small tmpfs for frame/log output (nvsipl can spew ~50 MB/s on a 0-frame error path;
# capping it on tmpfs keeps that off the real disk).
ensure_tmpfs() {
    mountpoint -q /tmp/live 2>/dev/null && return 0
    sudo mkdir -p /tmp/live
    sudo mount -t tmpfs -o size=64M tmpfs /tmp/live
}

# Canonical CSI virtual channel for a stream name.
vc_for() {
    case "$1" in
        depth)          echo 0 ;;
        rgb|color)      echo 1 ;;
        ir|infrared)    echo 2 ;;
        *) echo "vc_for: unknown stream '$1'" >&2; return 1 ;;
    esac
}

# Power-cycle the DS5 via the MAX20087 PoC controller (DS5 wedges run-to-run -> needs a clean power
# cycle before each fresh start).
power_cycle_ds5() {
    sudo i2cset -y $MUX_POC_BUS $MUX_POC_ADDR 0x01 0x00 2>/dev/null
    sleep 3
    sudo i2cset -y $MUX_POC_BUS $MUX_POC_ADDR 0x01 0x1f 2>/dev/null
    sleep 2
}

# gen_query <stream> [<stream> ...] — emit + compile + install a query plugin whose sensorInfo list
# is exactly the given streams (in order), each on its canonical VC.
gen_query() {
    local streams=("$@")
    mkdir -p /tmp/d457_tests
    local blocks="" i=0 s vc
    for s in "${streams[@]}"; do
        vc=$(vc_for "$s") || return 1
        [ $i -gt 0 ] && blocks+=","
        blocks+=$(cat <<EOF

          {
            "name": "D457",
            "id": $i,
            "description": "D457 $s stream on VC$vc",
            "i2cAddress": "0x1a",
            "numContext": 1,
            "isTriggerModeEnabled": false,
            "deviceIndex": $i,
            "virtualChannels": [
              {
                "vcIdSrc": $vc, "vcIdDst": $vc, "cfa": "rggb",
                "embeddedTopLines": 0, "embeddedBottomLines": 0,
                "inputFormat": "raw16", "width": __W__, "height": __H__, "fps": __F__,
                "isEmbeddedDataTypeEnabled": false
              }
            ]
          }
EOF
)
        i=$((i+1))
    done

    cat > "$QRY_SRC" <<EOF
// AUTO-GENERATED by tests/lib/common.sh gen_query — sensor list: ${streams[*]}
// Resolution is runtime env-driven (D457_WIDTH/HEIGHT/FPS) via __W__/__H__/__F__ token replace —
// mirrors query/d457_query.cpp so the test harness exercises the recompile-free resolution path.
#include <cstdlib>
#include <string>
extern "C" const char* CNvMQuery_GetJsonData(void)
{
    static std::string json = R"JSON(
[
  {
    "cameraConfigs": [
      {
        "name": "D457_Camera",
        "moduleDriverName": "D457",
        "type": "GMSL",
        "description": "RealSense D457 GMSL test config (${streams[*]})",
        "serInfo": { "name": "MAX9295", "i2cAddress": "0x40" },
        "linkMode": "LINK_MODE_GMSL2_6GBPS",
        "fsyncMode": "osc_manual",
        "mipiSettings": { "dphyRate": ${D457_DPHY_RATE:-2500000}, "phyMode": "dphy", "lanes": 4 },
        "sensorInfo": [$blocks
        ],
        "cryptoConfigName": ""
      }
    ]
  },
  {
    "platformTransportSettings": [
      {
        "name": "advantech_mic742_thor",
        "description": "Advantech MIC-742 Jetson Thor (D457 GMSL on CSI-A)",
        "boardIdPrefix": "NVIDIA Jetson AGX Thor",
        "enableMasks": [ "${D457_MASK:-0x0001}" ],
        "transportSettings": [
          {
            "name": "transportSettings_d457_AB",
            "type": "GMSL",
            "description": "GMSL transport for D457 - CSI-AB (2x4 capture descriptor, 4 Tegra lanes)",
            "csiPort": "csi-ab",
            "deserInfo": { "name": "Max96712GmslDeserializer", "i2cAddress": "0x29" },
            "powerControlInfo": {
              "moduleInfo": { "name": "MAX20087", "i2cAddress": "0x28" }
            },
            "i2cDevice": 9,
            "desI2CPort": 0,
            "phyMode": "dphy",
            "groupInitProg": true
          }
        ]
      }
    ]
  }
]
)JSON";
    auto envOr = [](const char* k, const char* d) {
        const char* v = std::getenv(k); return std::string((v && *v) ? v : d);
    };
    auto rep = [](std::string& s, const char* from, const std::string& to) {
        const std::string f(from);
        for (size_t p = s.find(f); p != std::string::npos; p = s.find(f, p + to.size())) s.replace(p, f.size(), to);
    };
    rep(json, "__W__", envOr("D457_WIDTH", "1280"));
    rep(json, "__H__", envOr("D457_HEIGHT", "720"));
    rep(json, "__F__", envOr("D457_FPS", "30.0"));
    return json.c_str();
}
EOF
    g++ -shared -fPIC -O2 -o /tmp/d457_tests/libnvsipl_qry_d457.so "$QRY_SRC" || return 1
    sudo cp /tmp/d457_tests/libnvsipl_qry_d457.so "$QRY_SO" || return 1
}

# run_streams <comma-list> <secs> [<label>] — gen query, power-cycle, run nvsipl_camera, assert each
# expected sensor has frames >= 25*secs with 0 drops and 0 dmesg faults. Returns 0 (pass) / 1 (fail).
run_streams() {
    local list="$1" secs="$2" label="${3:-$1}"
    local arr; IFS=',' read -ra arr <<< "$list"
    local n=${#arr[@]}
    ensure_tmpfs
    gen_query "${arr[@]}" || { fail "$label (query build failed)"; return 1; }
    sudo rm -f "$RUN_LOG"
    power_cycle_ds5
    local dmark="D457TEST_${RANDOM}_${RANDOM}"
    sudo sh -c "echo $dmark > /dev/kmsg" 2>/dev/null
    sudo env D457_STREAMS="$list" \
        timeout $((secs+15)) nvsipl_camera -H -R -0 -1 -2 -m 0x0001 -c D457_Camera -r "$secs" -s \
        > "$RUN_LOG" 2>&1
    sudo pkill -9 -x nvsipl_camera 2>/dev/null
    sleep 1

    local minf=$(( secs * 25 ))
    local ok=1 detail=""
    local i fc fd line
    for i in $(seq 0 $((n-1))); do
        line=$(grep -E "Sensor $i[[:space:]]+Frame captured:" "$RUN_LOG" | tail -1)
        fc=$(echo "$line" | grep -oE 'Frame captured: [0-9]+'   | grep -oE '[0-9]+$')
        fd=$(echo "$line" | grep -oE 'Frame drops: [0-9]+'      | grep -oE '[0-9]+$')
        local sname="${arr[$i]}"
        if [ -z "$fc" ]; then
            ok=0; detail+=" [$sname:NO-FRAMES]"
        elif [ "$fc" -lt "$minf" ]; then
            ok=0; detail+=" [$sname:fc=$fc<$minf]"
        elif [ "${fd:-1}" != "0" ]; then
            ok=0; detail+=" [$sname:drops=$fd]"
        else
            detail+=" [$sname:fc=$fc drops=0]"
        fi
    done
    local faults
    faults=$(sudo dmesg 2>/dev/null | sed -n "/$dmark/,\$p" | grep -icE 'chansel|pix_short|fault')
    [ "${faults:-0}" != "0" ] && { ok=0; detail+=" [dmesg-faults=$faults]"; }

    if [ "$ok" = "1" ]; then
        pass "$label —$detail (0 faults)"
        return 0
    fi
    fail "$label —$detail (faults=$faults)"
    echo "      (last config-query / error lines from run.log:)"
    grep -iE 'error|fail|GetConfig|NOTIF_ERROR' "$RUN_LOG" | head -5 | sed 's/^/      /'
    return 1
}

# run_res <stream> <w> <h> <fps> <secs> — run the ALREADY-INSTALLED (env-driven) query at the given
# resolution by setting D457_WIDTH/HEIGHT/FPS (recompile-free: the query reads them at launch). Asserts
# sensor 0 captured >= ~fps*secs*0.8 frames, 0 drops, 0 Tegra-VI faults. Caller does gen_query ONCE
# first (e.g. `gen_query depth`); this varies only the env, never rebuilding the query .so.
run_res() {
    local stream="$1" w="$2" h="$3" fps="$4" secs="$5"
    local label="${stream} ${w}x${h}@${fps}"
    ensure_tmpfs
    sudo rm -f "$RUN_LOG"
    local dmark="RES_${RANDOM}_${RANDOM}"
    sudo sh -c "echo $dmark > /dev/kmsg" 2>/dev/null
    sudo env D457_STREAMS="$stream" \
        D457_WIDTH="$w" D457_HEIGHT="$h" D457_FPS="$fps" \
        timeout $((secs+15)) nvsipl_camera -H -R -0 -1 -2 -m 0x0001 -c D457_Camera -r "$secs" -s \
        > "$RUN_LOG" 2>&1
    sudo pkill -9 -x nvsipl_camera 2>/dev/null
    sleep 1
    local line fc fd minf faults
    line=$(grep -E "Sensor 0[[:space:]]+Frame captured:" "$RUN_LOG" | tail -1)
    fc=$(echo "$line" | grep -oE 'Frame captured: [0-9]+' | grep -oE '[0-9]+$')
    fd=$(echo "$line" | grep -oE 'Frame drops: [0-9]+'    | grep -oE '[0-9]+$')
    minf=$(awk "BEGIN{printf \"%d\", $fps*$secs*0.8}")
    faults=$(sudo dmesg 2>/dev/null | sed -n "/$dmark/,\$p" | grep -icE 'chansel|pix_short|fault')
    if [ -n "$fc" ] && [ "$fc" -ge "$minf" ] && [ "${fd:-1}" = "0" ] && [ "${faults:-0}" = "0" ]; then
        pass "$label — fc=$fc (>=$minf) drops=0 faults=0"
        return 0
    fi
    fail "$label — fc=${fc:-NONE} (min $minf) drops=${fd:-?} faults=${faults:-?}"
    grep -iE 'error|fail|unsupported|invalid mode' "$RUN_LOG" | head -4 | sed 's/^/      /'
    return 1
}

summary() {
    echo
    echo "===================================================================="
    echo "  RESULT: $PASS_COUNT passed, $FAIL_COUNT failed"
    echo "===================================================================="
    [ "$FAIL_COUNT" = "0" ]
}
